'use client'

import { useState } from 'react'
import { AnimatePresence, motion } from 'motion/react'
import { ArrowUpRight, Check, ChevronRight, ShoppingBag, X } from 'lucide-react'
import { CartProvider, useCart } from './cart'

type Product = { id: string; name: string; world: string; price: string; image: string; tone: string; note: string }

const products: Product[] = [
  { id: 'orbit', name: 'ORBIT / 01', world: 'Space capsule', price: 'AED 780', image: '/media/terrain-orbit-01.png', tone: '#90a5ff', note: 'Reflective contour ink, orbital foil ribbon, 480gsm brushed cotton.' },
  { id: 'eclipse', name: 'UMBRA / 02', world: 'Space capsule', price: 'AED 760', image: '/media/terrain-eclipse-02.png', tone: '#e59a56', note: 'Sun-faded rust wash, eclipse dye placement, tonal topographic embroidery.' },
  { id: 'weather', name: 'WEATHER / 03', world: 'Space capsule', price: 'AED 820', image: '/media/terrain-weather-03.png', tone: '#a9c7ff', note: 'Planetary weather-map print, silver coordinate stitchwork, quilt-lined hood.' },
  { id: 'river', name: 'RIVER / 04', world: 'Light studies', price: 'AED 720', image: '/media/terrain-river-04.png', tone: '#b6a3ff', note: 'A continuous glass-river graphic in layered discharge inks and fine embroidery.' },
  { id: 'transit', name: 'TRANSIT / 05', world: 'City studies', price: 'AED 740', image: '/media/terrain-transit-05.png', tone: '#ef543d', note: 'Architectural print field, engineered placement and a single vermilion trajectory.' },
  { id: 'salt', name: 'SILT / 06', world: 'Earth studies', price: 'AED 740', image: '/media/terrain-salt-06.png', tone: '#c9d6cf', note: 'Aerial salt-flat print and tactile fingerprint map in water-based pigment.' },
]
const sizes = ['XS', 'S', 'M', 'L', 'XL']

export function TerrainStorefront() { return <CartProvider><Store /></CartProvider> }

function Store() {
  const [selected, setSelected] = useState<Product | null>(null)
  const { count, openCart } = useCart()
  return <div className="min-h-screen bg-[#080808] text-[#f5f2eb]">
    <div className="terrain-grid pointer-events-none fixed inset-0 opacity-40" />
    <header className="sticky top-0 z-40 border-b border-white/10 bg-[#080808]/85 px-4 backdrop-blur-xl"><nav className="mx-auto flex h-20 max-w-[1500px] items-center justify-between">
      <a href="#top" className="terrain-wordmark" aria-label="Terrain home"><span className="terrain-mark">⌁</span>TERRAIN</a>
      <div className="hidden items-center gap-7 text-[10px] font-medium uppercase tracking-[0.2em] text-white/55 md:flex"><a href="#collection" className="hover:text-white">Collection</a><a href="#ethos" className="hover:text-white">Field notes</a><span className="text-white">Dubai / Worldwide</span></div>
      <button onClick={openCart} className="group flex items-center gap-3 rounded-full border border-white/15 px-4 py-2 text-[10px] font-semibold uppercase tracking-[0.18em] transition hover:border-white hover:bg-white hover:text-black"><ShoppingBag className="h-4 w-4" />Bag <span className="grid h-5 min-w-5 place-items-center rounded-full bg-white/10 px-1 text-[9px] group-hover:bg-black group-hover:text-white">{count}</span></button>
    </nav></header>
    <main id="top" className="relative mx-auto max-w-[1500px] px-4 pb-24">
      <section className="grid min-h-[calc(100vh-5rem)] items-center gap-8 py-10 lg:grid-cols-[.84fr_1.16fr] lg:py-16"><div className="relative z-10 max-w-xl lg:pl-10"><motion.p initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} className="mb-6 text-[10px] font-semibold uppercase tracking-[0.34em] text-white/45">Terrain / Issue 001</motion.p><motion.h1 initial={{ opacity: 0, y: 25 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .1 }} className="terrain-title">WEAR A<br/><i>WORLD.</i></motion.h1><motion.p initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .2 }} className="mt-7 max-w-md text-base leading-relaxed text-white/60">Heavyweight hoodies made as places: light trails, weather systems, forgotten routes, and everything in between.</motion.p><motion.a initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .3 }} href="#collection" className="terrain-shine mt-9 inline-flex items-center gap-4 rounded-full bg-[#f5f2eb] px-6 py-4 text-[11px] font-bold uppercase tracking-[0.2em] text-black">Explore the drop <ArrowUpRight className="h-4 w-4" /></motion.a></div>
      <motion.button initial={{ opacity: 0, scale: .97 }} animate={{ opacity: 1, scale: 1 }} transition={{ duration: .8 }} onClick={() => setSelected(products[0])} className="group relative isolate min-h-[520px] overflow-hidden rounded-[2rem] border border-white/10 bg-[#121212] text-left"><img src={products[0].image} alt="Orbit hoodie" className="h-full w-full object-cover transition duration-700 group-hover:scale-[1.035]" /><div className="absolute inset-0 bg-gradient-to-t from-black/80 via-transparent to-transparent" /><div className="absolute inset-x-0 bottom-0 flex items-end justify-between p-7"><div><p className="text-[10px] uppercase tracking-[.26em] text-white/55">New / Space capsule</p><p className="mt-2 text-2xl font-medium">ORBIT / 01</p></div><span className="grid h-12 w-12 place-items-center rounded-full border border-white/30 bg-black/30 transition group-hover:bg-white group-hover:text-black"><ArrowUpRight className="h-5 w-5" /></span></div></motion.button></section>
      <section id="collection" className="scroll-mt-28 py-20 lg:px-10"><div className="mb-10 flex flex-col gap-5 border-b border-white/10 pb-8 md:flex-row md:items-end md:justify-between"><div><p className="text-[10px] font-semibold uppercase tracking-[.3em] text-white/45">Current coordinates</p><h2 className="mt-3 text-4xl font-medium tracking-[-.055em] sm:text-6xl">THE FIRST TERRAIN</h2></div><p className="max-w-xs text-sm leading-relaxed text-white/45">Six limited pieces. Every graphic is designed around the garment, never dropped on top of it.</p></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{products.map((product, index) => <ProductCard key={product.id} product={product} index={index} onSelect={setSelected} />)}</div></section>
      <section id="ethos" className="mx-0 mt-8 overflow-hidden rounded-[2rem] border border-white/10 bg-[#0e0e0e] p-8 lg:mx-10 lg:grid lg:grid-cols-[1fr_.8fr] lg:gap-24 lg:p-14"><div><p className="text-[10px] font-semibold uppercase tracking-[.32em] text-white/45">Field note 01</p><h2 className="mt-4 max-w-2xl text-4xl font-medium tracking-[-.055em] sm:text-6xl">PRINTS WITH A POINT OF VIEW.</h2></div><div className="mt-10 grid gap-5 text-sm leading-relaxed text-white/55 lg:mt-3"><p>Terrain treats a hoodie like a moving canvas. Artwork travels through seams, sleeves and pockets so it feels built in, not pasted on.</p><p className="border-l border-white/30 pl-5 text-white/75">Small releases. Serious cloth. No filler.</p></div></section>
    </main><footer className="border-t border-white/10 px-4 py-8 text-center text-[10px] uppercase tracking-[.22em] text-white/35">© 2026 Terrain Studio · Dubai / Worldwide</footer><ProductSheet product={selected} onClose={() => setSelected(null)} /></div>
}

function ProductCard({ product, index, onSelect }: { product: Product; index: number; onSelect: (product: Product) => void }) { return <motion.button initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, margin: '-40px' }} transition={{ delay: index * .05 }} onClick={() => onSelect(product)} className="group overflow-hidden rounded-[1.5rem] border border-white/10 bg-[#111] text-left"><div className="aspect-[.82] overflow-hidden"><img src={product.image} alt={product.name} loading="lazy" className="h-full w-full object-cover transition duration-700 group-hover:scale-105" /></div><div className="flex items-end justify-between p-5"><div><p className="text-[9px] font-semibold uppercase tracking-[.25em]" style={{ color: product.tone }}>{product.world}</p><h3 className="mt-2 text-xl font-medium">{product.name}</h3><p className="mt-1 text-xs text-white/45">{product.price}</p></div><ArrowUpRight className="mb-1 h-4 w-4 text-white/50 transition group-hover:-translate-y-1 group-hover:translate-x-1 group-hover:text-white" /></div></motion.button> }

function ProductSheet({ product, onClose }: { product: Product | null; onClose: () => void }) { const [size, setSize] = useState('M'); const { addItem } = useCart(); return <AnimatePresence>{product && <><motion.button aria-label="Close product" onClick={onClose} initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="fixed inset-0 z-50 bg-black/75 backdrop-blur-sm"/><motion.section initial={{ y: '100%' }} animate={{ y: 0 }} exit={{ y: '100%' }} transition={{ type: 'spring', damping: 28, stiffness: 260 }} className="fixed inset-x-0 bottom-0 z-[60] mx-auto max-h-[92vh] max-w-[1180px] overflow-y-auto rounded-t-[2rem] border border-white/15 bg-[#0b0b0b] p-5 shadow-2xl lg:p-8"><button onClick={onClose} className="absolute right-5 top-5 z-10 grid h-10 w-10 place-items-center rounded-full border border-white/15 bg-black/70 text-white"><X className="h-4 w-4" /></button><div className="grid gap-7 md:grid-cols-[1.1fr_.9fr]"><div className="overflow-hidden rounded-2xl bg-[#141414]"><img src={product.image} alt={product.name} className="h-full min-h-[360px] w-full object-cover" /></div><div className="flex flex-col py-3"><p className="text-[10px] font-semibold uppercase tracking-[.3em]" style={{ color: product.tone }}>{product.world}</p><h2 className="mt-3 text-4xl font-medium tracking-[-.055em]">{product.name}</h2><p className="mt-3 text-2xl text-white/85">{product.price}</p><p className="mt-7 text-sm leading-relaxed text-white/55">{product.note}</p><div className="mt-8"><div className="mb-3 flex justify-between text-[10px] uppercase tracking-[.22em] text-white/45"><span>Choose size</span><span>Fit guide</span></div><div className="flex gap-2">{sizes.map((option) => <button key={option} onClick={() => setSize(option)} className={`grid h-11 w-11 place-items-center rounded-full border text-xs transition ${size === option ? 'border-white bg-white text-black' : 'border-white/15 text-white/65 hover:border-white/50'}`}>{option}</button>)}</div></div><div className="mt-auto pt-8"><button onClick={() => addItem({ name: `${product.name} / ${size}`, price: product.price, image: product.image, accent: product.tone })} className="terrain-shine flex w-full items-center justify-center gap-3 rounded-full bg-white px-6 py-4 text-[11px] font-bold uppercase tracking-[.2em] text-black">Add to bag <ChevronRight className="h-4 w-4" /></button><p className="mt-4 flex items-center gap-2 text-[10px] uppercase tracking-[.16em] text-white/45"><Check className="h-3.5 w-3.5 text-white"/> Limited run · ships from Dubai</p></div></div></div></motion.section></>}</AnimatePresence> }
