'use client'

import { useState } from 'react'
import { AnimatePresence, motion } from 'motion/react'
import { ArrowDown, ArrowUpRight, Check, ChevronRight, ShoppingBag, X } from 'lucide-react'
import { CartProvider, useCart } from './cart'
import { terrainProducts, type TerrainProduct } from '@/lib/terrain-catalog'
import { GoogleAccountButton } from './google-account-button'

const products = terrainProducts
const sizes = ['XS', 'S', 'M', 'L', 'XL']

export function TerrainStorefront() { return <CartProvider><Store /></CartProvider> }

function Store() {
  const [selected, setSelected] = useState<TerrainProduct | null>(null)
  const { count, openCart } = useCart()
  return <div className="min-h-screen bg-[#080808] text-[#f5f2eb]">
    <div className="terrain-grid pointer-events-none fixed inset-0 opacity-40" />
    <header className="sticky top-0 z-40 border-b border-white/10 bg-[#080808]/85 px-4 backdrop-blur-xl"><nav className="mx-auto flex h-20 max-w-[1500px] items-center justify-between">
      <a href="#top" className="terrain-wordmark" aria-label="Terrain home"><span className="terrain-mark">⌁</span>TERRAIN</a>
      <div className="hidden items-center gap-7 text-[10px] font-medium uppercase tracking-[0.2em] text-white/55 md:flex"><a href="#collection" className="transition hover:text-white">Shop the drop</a><a href="#ethos" className="transition hover:text-white">Our point of view</a><span className="text-white/35">Issue 001</span></div>
      <div className="flex items-center gap-2"><GoogleAccountButton /><button onClick={openCart} className="group flex items-center gap-3 rounded-full border border-white/15 px-4 py-2 text-[10px] font-semibold uppercase tracking-[0.18em] transition hover:border-white hover:bg-white hover:text-black"><ShoppingBag className="h-4 w-4" />Bag <span className="grid h-5 min-w-5 place-items-center rounded-full bg-white/10 px-1 text-[9px] group-hover:bg-black group-hover:text-white">{count}</span></button></div>
    </nav></header>
    <main id="top" className="relative mx-auto max-w-[1500px] px-4 pb-24">
      <section className="relative grid min-h-[calc(100vh-5rem)] items-center gap-9 overflow-hidden py-8 lg:grid-cols-[.88fr_1.12fr] lg:py-14"><div className="absolute left-[13%] top-[18%] h-64 w-64 rounded-full bg-violet-500/10 blur-[120px]"/><div className="relative z-10 max-w-xl lg:pl-10"><motion.p initial={{ opacity: 0, y: 18 }} animate={{ opacity: 0.8, y: 0 }} className="mb-7 flex items-center gap-3 text-[10px] font-semibold uppercase tracking-[0.34em] text-white/55"><span className="h-px w-8 bg-white/40"/>Terrain / Volume one</motion.p><motion.h1 initial={{ opacity: 0, y: 25 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .1 }} className="terrain-title leading-[.82]">THE WORLD<br/>ON YOUR<br/><i>SLEEVE.</i></motion.h1><motion.p initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .2 }} className="mt-8 max-w-md text-base leading-relaxed text-white/60">Not merch. Moving canvases for night drives, cosmic weather, lost highways and the places you only see once.</motion.p><motion.div initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .3 }} className="mt-9 flex flex-wrap items-center gap-4"><a href="#collection" className="terrain-shine inline-flex items-center gap-4 rounded-full bg-[#f5f2eb] px-6 py-4 text-[11px] font-bold uppercase tracking-[0.2em] text-black">Enter the drop <ArrowUpRight className="h-4 w-4" /></a><a href="#ethos" className="inline-flex items-center gap-2 px-3 py-4 text-[10px] font-semibold uppercase tracking-[.18em] text-white/55 transition hover:text-white">Why Terrain <ArrowDown className="h-3.5 w-3.5"/></a></motion.div><div className="mt-14 flex items-center gap-7 text-[10px] uppercase tracking-[.18em] text-white/40"><span><b className="font-medium text-white">72</b> pieces</span><span><b className="font-medium text-white">480gsm</b> cloth</span><span><b className="font-medium text-white">Dubai</b> based</span></div></div>
      <motion.button initial={{ opacity: 0, scale: .97 }} animate={{ opacity: 1, scale: 1 }} transition={{ duration: .8 }} onClick={() => setSelected(products[0])} className="group relative isolate min-h-[540px] overflow-hidden rounded-[2rem] border border-white/10 bg-[#121212] text-left"><img src={products[0].image} alt="Orbit hoodie" className="absolute inset-0 h-full w-full object-cover transition duration-700 group-hover:scale-[1.035]" /><div className="absolute inset-0 bg-gradient-to-t from-black/90 via-black/5 to-black/20"/><div className="absolute right-5 top-5 rounded-full border border-white/20 bg-black/30 px-4 py-2 text-[9px] font-semibold uppercase tracking-[.2em] backdrop-blur">The first terrain</div><div className="absolute inset-x-0 bottom-0 flex items-end justify-between p-7"><div><p className="text-[10px] uppercase tracking-[.26em] text-white/55">Featured / Space capsule</p><p className="mt-2 text-3xl font-medium">ORBIT / 01</p><p className="mt-2 text-xs text-white/55">AED 780 · Limited release</p></div><span className="grid h-12 w-12 place-items-center rounded-full border border-white/30 bg-black/30 transition group-hover:bg-white group-hover:text-black"><ArrowUpRight className="h-5 w-5" /></span></div></motion.button></section>
      <section id="collection" className="scroll-mt-28 py-20 lg:px-10"><div className="mb-10 flex flex-col gap-5 border-b border-white/10 pb-8 md:flex-row md:items-end md:justify-between"><div><p className="text-[10px] font-semibold uppercase tracking-[.3em] text-white/45">Current coordinates</p><h2 className="mt-3 text-4xl font-medium tracking-[-.055em] sm:text-6xl">THE TERRAIN EDIT</h2></div><p className="max-w-xs text-sm leading-relaxed text-white/45">Seventy-two handpicked pieces. Every graphic is designed around the garment, never dropped on top of it.</p></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{products.map((product, index) => <ProductCard key={product.id} product={product} index={index} onSelect={setSelected} />)}</div></section>
      <section id="ethos" className="mx-0 mt-8 overflow-hidden rounded-[2rem] border border-white/10 bg-[#0e0e0e] p-8 lg:mx-10 lg:grid lg:grid-cols-[1fr_.8fr] lg:gap-24 lg:p-14"><div><p className="text-[10px] font-semibold uppercase tracking-[.32em] text-white/45">Field note 01</p><h2 className="mt-4 max-w-2xl text-4xl font-medium tracking-[-.055em] sm:text-6xl">PRINTS WITH A POINT OF VIEW.</h2></div><div className="mt-10 grid gap-5 text-sm leading-relaxed text-white/55 lg:mt-3"><p>Terrain treats a hoodie like a moving canvas. Artwork travels through seams, sleeves and pockets so it feels built in, not pasted on.</p><p className="border-l border-white/30 pl-5 text-white/75">Small releases. Serious cloth. No filler.</p></div></section>
    </main><footer className="border-t border-white/10 px-4 py-8 text-center text-[10px] uppercase tracking-[.22em] text-white/35">© 2026 Terrain Studio · Dubai / Worldwide</footer><ProductSheet product={selected} onClose={() => setSelected(null)} /></div>
}

function ProductCard({ product, index, onSelect }: { product: TerrainProduct; index: number; onSelect: (product: TerrainProduct) => void }) { return <motion.button initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, margin: '-40px' }} transition={{ delay: Math.min(index, 12) * .05 }} onClick={() => onSelect(product)} className="group overflow-hidden rounded-[1.5rem] border border-white/10 bg-[#111] text-left"><div className="aspect-[.82] overflow-hidden"><img src={product.image} alt={product.name} loading="lazy" className="h-full w-full object-cover transition duration-700 group-hover:scale-105" /></div><div className="flex items-end justify-between p-5"><div><p className="text-[9px] font-semibold uppercase tracking-[.25em]" style={{ color: product.tone }}>{product.world}</p><h3 className="mt-2 text-xl font-medium">{product.name}</h3><p className="mt-1 text-xs text-white/45">{product.price}</p></div><ArrowUpRight className="mb-1 h-4 w-4 text-white/50 transition group-hover:-translate-y-1 group-hover:translate-x-1 group-hover:text-white" /></div></motion.button> }

function ProductSheet({ product, onClose }: { product: TerrainProduct | null; onClose: () => void }) { const [size, setSize] = useState('M'); const { addItem } = useCart(); return <AnimatePresence>{product && <><motion.button aria-label="Close product" onClick={onClose} initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="fixed inset-0 z-50 bg-black/75 backdrop-blur-sm"/><motion.section initial={{ y: '100%' }} animate={{ y: 0 }} exit={{ y: '100%' }} transition={{ type: 'spring', damping: 28, stiffness: 260 }} className="fixed inset-x-0 bottom-0 z-[60] mx-auto max-h-[92vh] max-w-[1180px] overflow-y-auto rounded-t-[2rem] border border-white/15 bg-[#0b0b0b] p-5 shadow-2xl lg:p-8"><button onClick={onClose} className="absolute right-5 top-5 z-10 grid h-10 w-10 place-items-center rounded-full border border-white/15 bg-black/70 text-white"><X className="h-4 w-4" /></button><div className="grid gap-7 md:grid-cols-[1.1fr_.9fr]"><div className="space-y-3"><div className="overflow-hidden rounded-2xl bg-[#141414]"><img src={product.image} alt={product.name} className="h-full min-h-[360px] w-full object-cover" /></div><div><p className="mb-2 text-[9px] font-semibold uppercase tracking-[.22em] text-white/45">All angles / construction reference</p><img src="/media/terrain-garment-views-01.png" alt="Hoodie front, back, profile and detail views" className="w-full rounded-xl border border-white/10" /></div></div><div className="flex flex-col py-3"><p className="text-[10px] font-semibold uppercase tracking-[.3em]" style={{ color: product.tone }}>{product.world}</p><h2 className="mt-3 text-4xl font-medium tracking-[-.055em]">{product.name}</h2><p className="mt-3 text-2xl text-white/85">{product.price}</p><p className="mt-7 text-sm leading-relaxed text-white/55">{product.note}</p><div className="mt-8"><div className="mb-3 flex justify-between text-[10px] uppercase tracking-[.22em] text-white/45"><span>Choose size</span><span>Fit guide</span></div><div className="flex gap-2">{sizes.map((option) => <button key={option} onClick={() => setSize(option)} className={`grid h-11 w-11 place-items-center rounded-full border text-xs transition ${size === option ? 'border-white bg-white text-black' : 'border-white/15 text-white/65 hover:border-white/50'}`}>{option}</button>)}</div></div><div className="mt-auto pt-8"><button onClick={() => addItem({ name: `${product.name} / ${size}`, price: product.price, image: product.image, accent: product.tone })} className="terrain-shine flex w-full items-center justify-center gap-3 rounded-full bg-white px-6 py-4 text-[11px] font-bold uppercase tracking-[.2em] text-black">Add to bag <ChevronRight className="h-4 w-4" /></button><p className="mt-4 flex items-center gap-2 text-[10px] uppercase tracking-[.16em] text-white/45"><Check className="h-3.5 w-3.5 text-white"/> Limited run · ships from Dubai</p></div></div></div></motion.section></>}</AnimatePresence> }
